version: '3.1'
services:
  db:
    image: postgres
    container_name: sam-serverless-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ../db/migrations/000001_create_books_table.up.sql:/docker-entrypoint-initdb.d/init.sql
